### ISSUE TITLE
option to specify angular momentum w.r.t root frame.

### ISSUE THREAD

**Issue by stevenjj** [junhyeokahn/PnC#2]
Hi Junhyeok,
https://github.com/junhyeokahn/PnC/blob/2361515d7f27410b98ee109e684ce4f6d606f74d/PnC/RobotSystem/RobotSystem.cpp#L206

Currently the momentum equations are w.r.t world frame. We probably should include the option to represent momentum w.r.t the root frame orientation. 

For example, when running, we may want to only control the body pitch direction of angular momentum and allow some yaw or roll rotations. If we represent angular momentum w.r.t root frame, the selection matrix will only be 1s and 0s.  But since the angular momentum is represented in the world frame , the selection matrix will need a rotation matrix to properly enforce only controlling the pitch angular momentum control.

Perhaps the easiest is to use the root frame orientation as the CoM's orientation by modifying this line:

https://github.com/junhyeokahn/PnC/blob/2361515d7f27410b98ee109e684ce4f6d606f74d/PnC/RobotSystem/RobotSystem.cpp#L223

What do you think?

**Comment by junhyeokahn** [comment]
I see why you need the centroidal momentum in the root frame.
Can we simply achieve it by multiplying an adjoint mapping?
For example,
```local_angular_momentum = AdT * global_angular_momentum```
where AdT is the adjoint mapping from the global frame to the local frame.
Corresponding ``Acent_local``` matrix mapping joint velocity from centroidal momentum could be equivalently achieved with ```AdT * Acent```.
Please correct me if I am wrong.

**Comment by stevenjj** [comment]
It might work since the linear term in the adjoint mapping would be p = 0. So it's just a diagonal R matrix. I suppose to be thorough we have to compare it against computing the following:
````
O_R_com = O_R_base
com_R_gl = O_R_com.transpose() * R_gl // from R_gl = O_R_com* com_R_gl
````
Maybe an equivalence can also be made if we can show we can factor out the rotation matrix.

**Comment by junhyeokahn** [comment]
Yes, I think I could incorporate that option in a few days.
Or, you are also welcome to make changes and push if you are fine with it.

**Comment by junhyeokahn** [comment]
Hello, sorry for taking this too long.

I think the best place to implement this feature is inside the child task class.
For now, we are pre- and post- multiplying a rotation matrix (of the frame of interest) to express task gains in the local frame.
Here is my current [implementation](https://github.com/junhyeokahn/PnC/blob/210ac90af3fdc95c6c64e23677b3c786abba8e5d/pnc/draco_pnc/draco_task/draco_angular_momentum_task.cpp#L18) and this resides in the child task class (i.e. in the ```draco_task``` directory), since the frame of interest is robot-specific.

Also, I am implementing ```RobotSystem``` using ```pinocchio``` which just returns the centroidal quantities w.r.t the world frame.
Considering the compatibility of ```dart``` and ```pinocchio```, it makes more sense to convert global quantities to local quantities using a rotation matrix.

**Comment by stevenjj** [comment]
Alright sounds good. I think creating a child task class that implements the rotation at the frame of interest is the right approach for compatibility with different libraries. 

Perhaps the action item here is to create an example child class that shows how that centroidal angular momentum is rotated in the frame of interest (e.g. root frame/base frame).
